# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd1e75c31a44dd74ef6a2efaf68387375c011f8cd42ec78270f5722cde254e2347ba349147a08f121e8941c36dde76d1e1b1d378247d5db00ed9bf4e01f24cd

test:
  secret_key_base: 9a07b54caf96b623aa480551bcb5d564d6bf8e9b07d8195503101e5ebb8c4d9f85b59cb7abadcf60917855b659464e10e075bced97d2eb1ab93cd9221c9f391b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
